name: sound-charts

containerEngine: docker

extensions:
- name: dapr
  services:
    tileset-service:
      components-path: ./SoundCharts.Explorer.TilesetService/Components/Local

services:
- name: tile-service
  project: ./SoundCharts.Explorer.TileService/SoundCharts.Explorer.TileService.csproj
- name: tileset-service
  project: ./SoundCharts.Explorer.TilesetService/SoundCharts.Explorer.TilesetService.csproj
- name: yarp
  project: ./SoundCharts.Explorer.Ingress/SoundCharts.Explorer.Ingress.csproj
  bindings:
   - port: 8081
- name: nginx
  image: nginx:latest
  bindings:
    - port: 8080
      containerPort: 9090
      protocol: http
  volumes:
    - source: nginx.conf
      target: /etc/nginx/conf.d/default.conf
