name: Build Xamarin.MacOS app

on: [push]

jobs:
  cli-build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2   

    - name: Setup .NET SDK 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
   
    - name: Install Dependencies
      run: |
        dotnet restore src/SoundCharts.Explorer.Cli/SoundCharts.Explorer.Cli.csproj

    - name: Build
      run: |
        dotnet build src/SoundCharts.Explorer.Cli/SoundCharts.Explorer.Cli.csproj --configuration Release

  services-build:

    runs-on: ubuntu-latest

    env:
      REGISTRY: soundcharts.azurecr.io

    steps:
    - name: Generate build ID
      id: prep
      run: |
        branch=${GITHUB_REF##*/}
        sha=${GITHUB_SHA::8}
        ts=$(date +%s)
        echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"          

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build tileset-service
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: src/SoundCharts.Explorer.TilesetService/Dockerfile
        push: true
        tags: ${{ REGISTRY }}/tileset-service:${{ steps.prep.outputs.BUILD_ID }}

  mac-build:

    runs-on: macos-11

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2   

    - name: Setup .NET SDK 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --mac=8.2
    
    - name: Install Dependencies
      run: |
        nuget restore src/SoundCharts.Explorer.Common/SoundCharts.Explorer.Common.csproj -SolutionDirectory src
        nuget restore src/SoundCharts.Explorer.MacOS/SoundCharts.Explorer.MacOS.csproj -SolutionDirectory src

    - name: Build
      run: msbuild src/SoundCharts.Explorer.MacOS/SoundCharts.Explorer.MacOS.csproj /p:Configuration=Release /t:Rebuild

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: "src/SoundCharts.Explorer.MacOS/bin/Release/SoundCharts Explorer-1.0.pkg"
